version: '2'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=9000
    volumes:
      - ./momoidentity-keycloak:/opt/keycloak/themes/momoidentity-keycloak:Z
    ports:
     - 9000:9000